### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Gonimbrasia** [WorldObservationLog/AppleMusicDecrypt#18]
I am getting this error using Android Studio:-

```
2024-06-10 01:00:14.335 | ERROR    | main:<module>:16 - An error has been caught in function '<module>', process 'MainProcess' (7552), thread 'MainThread' (2988):
Traceback (most recent call last):

> File "D:\Programs\AppleMusicDecrypt\main.py", line 16, in <module>

  File "D:\Programs\AppleMusicDecrypt\src\utils.py", line 74, in helper

  File "D:\Programs\AppleMusicDecrypt\src\utils.py", line 68, in process

  File "D:\Programs\AppleMusicDecrypt\src\rip.py", line 93, in rip_song

  File "D:\Programs\AppleMusicDecrypt\src\mp4.py", line 104, in extract_song

  File "D:\Programs\AppleMusicDecrypt\subprocess.py", line 548, in run

  File "D:\Programs\AppleMusicDecrypt\subprocess.py", line 1026, in init

  File "D:\Programs\AppleMusicDecrypt\subprocess.py", line 1538, in _execute_child

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Overliinez** [comment]
I got the same error, using WSA

**Comment by dardenbt** [comment]
> I got the same error, using WSA

I also went to the project page and downloaded the "src" folder and put that in the same folder as the executable. Maybe that did nothing but I got it to work so idk

**Comment by Overliinez** [comment]
Thank you, I did not have to try your second comment but the first one definitely helped!

**Comment by Gonimbrasia** [comment]
In my case mp4extract and mp4edit were not added to PATH. I'm now getting a different error.
